export const data = [

  {
    "date": "Saturday, June 7th, 2025",
    "highTemp": 51.0,
    "lowTemp": 65.0,
    "precip": 0.35,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Weld tiller, measure and stake out area. Remove weeds, mow, till soil to break up thatch, hand sift thatch from soil and dispose",
    "eveningActivities": "None",
    "manHours": ["Construction", 15.0],
    "purchases": ["Seeds, Stakes, Twine", 90.00],
    "harvest": ["Zucchini", 4.0],
    "preserve": ["Potatoes", "Two five-gallon buckets"],
    "image_url": ["https://i.ibb.co/Nn9c7PpL/20250607-1.jpg", "https://i.ibb.co/gZjk32Vv/20250611-C.jpg", "https://i.ibb.co/SwJBs93V/20250607-3.jpg", "https://i.ibb.co/5gD3sVhQ/20250607-2.jpg", "https://i.ibb.co/Wv4K4Bnr/20250611-D.jpg", "https://i.ibb.co/JR1HQymf/20250611-I.jpg", "https://i.ibb.co/Rw4gVLC/20250607-4.jpg"],
  },
  {
    "date": "Sunday, June 8th, 2025",
    "highTemp": 70.0,
    "lowTemp": 55.0,
    "precip": 0.0,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Spread manure, till into soil, create garden layout, source fencing from closest supplier",
    "eveningActivities": "Trip to farm supply store to purchase fencing",
    "manHours": ["Construction", 22.0],
    "purchases": ["Fenceposts", 300.00],
    "harvest": ["Beans", 200.0, "Cucumbers", 3.0],
    "preserve": ["Tomatoes", "Four one-lb bags"],
    "image_url": ["https://i.ibb.co/XkdvDHBN/20250608-1.jpg", "https://i.ibb.co/gZt8Cd3S/20250608-2.jpg", "https://i.ibb.co/HDfhtFGv/20250608-5.jpg", "https://i.ibb.co/2Yt1y0LK/20250608-4.jpg", "https://i.ibb.co/zWBLHf1G/20250608-6.jpg", "https://i.ibb.co/1JKbVVkw/20250608-7.jpg"],
  },
  {
    "date": "Wednesday, June 11th, 2025",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "None",
    "eveningActivities": "Pick up fencing 2 heavy duty, 1 light duty, work gloves, and zip ties from Menards. Pick up fence pounder/work gloves/hoe/ladder from parents.",
    "manHours": ["Construction", 3.0],
    "purchases": ["Fencing", 90.00],
    "harvest": ["Zucchini", 4.0],
    "preserve": ["Cucumbers", "Six pint jars of pickles"],
    "image_url": ["https://i.ibb.co/p6Wsmwt1/20250611-A.jpg", "https://i.ibb.co/2HfpBqh/20250611-1.jpg", "https://i.ibb.co/JR9RygDz/20250611-3.jpg"],
  },
  {
    "date": "Friday, June 13th, 2025",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Installed fenceposts.  This required one of us on the ground holding the 10' post, and the other on a ladder with a post pounder. ",
    "eveningActivities": "",
    "manHours": ["Install fenceposts", 6.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/mrzY75sv/20250614-A.jpg"],
  },
  {
    "date": "Saturday, June 14th",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Installed 200' fencing on garden.  This required holding the rolled fence taught while the other person zip tied the fence to the posts.",
    "eveningActivities": "",
    "manHours": ["Install fencing", 8.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/pr6tWbBC/20250613-1.jpg"],
  },
  {
    "date": "Thursday, June 19th",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Purchased new sprinkler, weeded.",
    "eveningActivities": "",
    "manHours": ["Weeding", 2.0],
    "purchases": ["Sprinkler", 20.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/BVnjd8jC/20250619-1.jpg", "https://i.ibb.co/5xR8yjp5/20250619-B.jpg", "https://i.ibb.co/L7szd9z/20250619-C.jpg", "https://i.ibb.co/fVd281k3/20250619-D.jpg"],
  },
  {
    "date": "Monday, June 23rd",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Weeding",
    "eveningActivities": "",
    "manHours": ["Weeding", 3.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/5gchf2zK/20250623-1.jpg", "https://i.ibb.co/LdWp2wXh/20250623-4.jpg"],
  },
  {
    "date": "Sunday, June 29th",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Weeding",
    "eveningActivities": "",
    "manHours": ["Weeding", 3.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/GQWxHydV/20250629-1.jpg", "https://i.ibb.co/MWcVdS6/20250629-2.jpg", "https://i.ibb.co/Jjjmznq1/20250629-3.jpg", "https://i.ibb.co/VcLxtd3w/20250629-4.jpg", "https://i.ibb.co/tTg7d1xy/20250629-5.jpg", "https://i.ibb.co/4RBP9jDT/20250629-6.jpg"],
  },
  {
    "date": "Wednesday, July 2nd",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Weeding",
    "eveningActivities": "",
    "manHours": ["Weeding", 4.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/7dvm1jxy/20250702-1.jpg", "https://i.ibb.co/Z6XjZqFR/20250702-2.jpg", "https://i.ibb.co/Rq83bvC/20250702-11.jpg", "https://i.ibb.co/SwSdw3gd/20250702-12.jpg", "https://i.ibb.co/359ZT53K/20250702-13.jpg", "https://i.ibb.co/Z118MfwJ/20250702-14.jpg", "https://i.ibb.co/B5qDYTwm/20250702-16.jpg"],
  },
  {
    "date": "Saturday, July 5th",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Weeding",
    "eveningActivities": "",
    "manHours": ["Weeding", 4.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/TDPC2WyK/20250705-A.jpg"],
  },
  {
    "date": "Monday, July 7th",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Weeding",
    "eveningActivities": "",
    "manHours": ["Weeding", 4.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/Xx6Yfqzn/20250707-9.jpg", "https://i.ibb.co/1YYPzw4y/20250707-10.jpg", "https://i.ibb.co/v4kjbhzn/20250707-3.jpg", "https://i.ibb.co/Y4rYLd0r/20250707-4.jpg", "https://i.ibb.co/vvzqZg7q/20250707-7.jpg", "https://i.ibb.co/PZbMDBZt/20250707-6.jpg"],
  },
  {
    "date": "Tuesday, July 22nd",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Weeding",
    "eveningActivities": "",
    "manHours": ["Weeding", 4.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/4wHD2XfW/20250722-2.jpg", "https://i.ibb.co/DqbD7LQ/20250722-18.jpg", "https://i.ibb.co/cKgZrgS8/20250722-8.jpg", "https://i.ibb.co/fV2H96Ls/20250722-11.jpg"],
  },
  {
    "date": "Thursday, July 31st",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Weeding",
    "eveningActivities": "",
    "manHours": ["Weeding", 4.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/zWqKhp2Z/20250731-A.jpg", "https://i.ibb.co/gbTdBvVr/20250731-B.jpg", "https://i.ibb.co/tP4LwDZy/20250731-1.jpg"],
  },
  {
    "date": "Thursday, August 14th",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Weeding, harvested zucchini, squash, and beets",
    "eveningActivities": "",
    "manHours": ["Harvest/Weeding", 6.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/93p4x2rf/20250813-A.jpg", "https://i.ibb.co/v6hG2jys/20250813-C.jpg", "https://i.ibb.co/Tz5YM26/20250814-2.jpg"],
  },
  {
    "date": "Wednesday, August 20th",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Canned beans and beets.",
    "eveningActivities": "",
    "manHours": ["Canning", 8.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/nNnQBXqq/20250820-1.jpg"],
  },
  {
    "date": "Thursday, August 21st",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Canned cauliflower and cucumbers",
    "eveningActivities": "",
    "manHours": ["Canning", 8.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/M51H699k/20250821-1.jpg"],
  },
  {
    "date": "Friday, August 29th",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Harvested, cleaned, diced, and bagged onions",
    "eveningActivities": "",
    "manHours": ["Preserving", 8.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/SDhJPZPZ/20250829-1.jpg"],
  },
  {
    "date": "Friday, September 5th",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Attended a sauerkraut party, chopped approximately 200lbs of cabbage.",
    "eveningActivities": "",
    "manHours": ["Chopping", 4.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/s8vxm83/20250905-3.jpg", "https://i.ibb.co/KxG2FLsQ/20250905-1.jpg", "https://i.ibb.co/N6v8ngLP/20250905-8.jpg"],
  },
  {
    "date": "Thursday, September 11th",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Harvested the potatoes, approximately two five-gallon bucket yield.",
    "eveningActivities": "",
    "manHours": ["Harvest", 2.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/pj0H8jXy/20250911-1.jpg"],
  },
  {
    "date": "Sunday, September 28th",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Potato Party! This was an event that used approximately half our harvest to create six 10-serving meals.",
    "eveningActivities": "",
    "manHours": ["", 0.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/Vp5xV4HY/20250927-1.jpg", "https://i.ibb.co/ZpkQbzZ1/20250927-2.jpg"],
  },
  {
    "date": "Thursday, October 2nd",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Harvested, cleaned, chopped, blanched all the carrots.",
    "eveningActivities": "",
    "manHours": ["Preserving", 8.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/hJmvVx5P/20251002-1.jpg", "https://i.ibb.co/vvgK28YS/20251002-2.jpg", "https://i.ibb.co/WvnfSndv/20251003-A.jpg"],
  },
  {
    "date": "Thursday, October 9th",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "N/A",
    "dayActivities": "Attended a sauerkraut canning party",
    "eveningActivities": "",
    "manHours": ["Canning", 4.0],
    "purchases": ["", 0.00],
    "harvest": ["", 0.0],
    "preserve": ["", ""],
    "image_url": ["https://i.ibb.co/GSTF8cN/20251009-1.jpg", "https://i.ibb.co/yF9X3zdx/20251009-2.jpg", "https://i.ibb.co/q3cjVcSx/20251009-3.jpg"],
  },
]


  // {
  //   "date": "",
  //   "highTemp": 66.0,
  //   "lowTemp": 49.0,
  //   "precip": 0.79,
  //   "watering": "N/A",
  //   "visitors": "N/A",
  //   "dayActivities": "None",
  //   "eveningActivities": "",
  //   "manHours": ["", 0.0],
  //   "purchases": ["", 0.00],
  //   "harvest": ["", 0.0],
  //   "preserve": ["", ""],
  //   "image_url": ["", "", ""],
  // },