export const data = [

  {
    "date": "Saturday, June 7th, 2025",
    "highTemp": 51.0,
    "lowTemp": 65.0,
    "precip": 0.35,
    "watering": "N/A",
    "visitors": "None",
    "dayActivities": "Weld tiller, measure and stake out area. Remove weeds, mow, till soil to break up thatch, hand sift thatch from soil and dispose",
    "eveningActivities": "None",
    "manHours": ["Construction", 15.0],
    "purchases": ["Seeds, Stakes, Twine", 90.00],
    "harvest": ["Zucchini", 4.0],
    "preserve": ["Potatoes", "Two five-gallon buckets"],
    "image_url": ["https://picsum.photos/200", "https://picsum.photos/300", "https://picsum.photos/400"],
  },
  {
    "date": "Sunday, June 8th, 2025",
    "highTemp": 70.0,
    "lowTemp": 55.0,
    "precip": 0.0,
    "watering": "N/A",
    "visitors": "Joslyn Dunbar",
    "dayActivities": "Spread manure, till into soil, create garden layout, source fencing from closest supplier",
    "eveningActivities": "Trip to farm supply store to purchase fencing",
    "manHours": ["Construction", 22.0],
    "purchases": ["Fenceposts", 300.00],
    "harvest": ["Beans", 200.0, "Cucumbers", 3.0],
    "preserve": ["Tomatoes", "Four one-lb bags"],
    "image_url": ["https://picsum.photos/400", "https://picsum.photos/300", "https://picsum.photos/200"],
  },
  {
    "date": "Monday, June 9th, 2025",
    "highTemp": 66.0,
    "lowTemp": 49.0,
    "precip": 0.79,
    "watering": "N/A",
    "visitors": "None",
    "dayActivities": "None",
    "eveningActivities": "Pick up fencing 2 heavy duty, 1 light duty, work gloves, and zip ties from Menards. Pick up fence pounder/work gloves/hoe/ladder from parents.",
    "manHours": ["Construction", 3.0],
    "purchases": ["Fencing", 90.00],
    "harvest": ["Zucchini", 4.0],
    "preserve": ["Cucumbers", "Six pint jars of pickles"],
    "image_url": ["https://picsum.photos/300", "https://picsum.photos/400", "https://picsum.photos/300"],
  },

]

// {
//   "date": "",
//   "highTemp": 0.0,
//   "lowTemp": 0.0,
//   "precip": 0.0,
//   "watering": "",
//   "visitors": "None",
//   "dayActivities": "",
//   "eveningActivities": "",
//   "manHours": ["Paul", 0.0, "Derek", 0.0],
//   "purchases": ["", 0.00],
//   "image_url": ["https://picsum.photos/200"],
// },